name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: jpetrucciani/bandit-check@master
      with:
        path: '.'
        bandit_flags: '-lll -o output.json -f json'
